const $=id=>document.getElementById(id);let payload=null;
const money=v=>v==null?"-":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(v))+" USDT";
const number=(v,d=2)=>v==null?"-":Number(v).toFixed(d);
function canvas(id,series,color){const el=$(id),r=devicePixelRatio||1,w=el.clientWidth,h=el.clientHeight;el.width=w*r;el.height=h*r;const c=el.getContext("2d");c.scale(r,r);c.clearRect(0,0,w,h);if(series.length<2)return;const lo=Math.min(...series),hi=Math.max(...series),pad=18,y=v=>pad+(hi-v)/(hi-lo||1)*(h-pad*2);c.strokeStyle="#263047";for(let i=1;i<5;i++){c.beginPath();c.moveTo(0,h*i/5);c.lineTo(w,h*i/5);c.stroke()}c.strokeStyle=color;c.lineWidth=2;c.beginPath();series.forEach((v,i)=>{const x=pad+i/(series.length-1)*(w-pad*2);i?c.lineTo(x,y(v)):c.moveTo(x,y(v))});c.stroke()}
function events(id,items){$(id).replaceChildren(...items.slice(-80).reverse().map(item=>{const e=document.createElement("div");e.className="event";const h=document.createElement("strong"),p=document.createElement("p");h.textContent=`${item.symbol||"SYSTEM"} - ${item.event||item.action}`;p.textContent=`${new Date(item.timestamp).toLocaleString("en-US")} - ${item.reason||""}`;e.append(h,p);return e}))}
function scanner(rows){$("scanner").replaceChildren(...rows.map(item=>{const tr=document.createElement("tr");[item.rank??"-",item.symbol,item.eligible?"ELIGIBLE":"BLOCKED",number(item.momentum_atr),number(item.volume_zscore),`${number(item.spread_bps)} bps`,money(item.depth),number(item.liquidity_score),number(item.manipulation_risk),(item.reasons||[]).join(", ")||"Ready"].forEach((value,i)=>{const td=document.createElement("td");td.textContent=value;if(i===2)td.className=item.eligible?"ok":"blocked";tr.append(td)});return tr}))}
function market(){if(!payload)return;const symbols=payload.stream.symbols||{},state=symbols[$("symbol").value]||{},c=state.latest_candle;$("market-detail").textContent=`Mark ${money(state.mark_price)} - Index ${money(state.index_price)} - Spread ${number(state.spread_bps)} bps - Funding ${number(Number(state.funding_rate)*100,4)}%`;canvas("price-chart",c?[Number(c.open),Number(c.low),Number(c.high),Number(c.close)]:[],"#4fd1c5")}
function render(data){payload=data;$("updated").textContent=`Updated ${new Date(data.generated_at).toLocaleTimeString("en-US")}`;if(!data.available){$("empty-copy").textContent=data.error;return}$("empty").classList.add("hidden");$("dashboard").classList.remove("hidden");const stream=data.stream,report=data.report,badge=$("stream");badge.textContent=stream.connected?"STREAMING":"STALE / STOPPED";badge.className=`pill ${stream.connected?"safe":"danger"}`;$("equity").textContent=money(report.final_equity);$("pnl").textContent=`Net PnL ${money(report.net_pnl)}`;$("position").textContent=report.position?`${report.position.side.toUpperCase()} ${report.position.symbol}`:"FLAT";$("position-detail").textContent=report.position?`Qty ${report.position.quantity} - ${report.position.leverage}x`:"No exposure";const risk=report.risk||{};$("risk").textContent=`${number(Number(risk.risk_per_trade||.005)*100)}% per trade`;$("limits").textContent=`${number(Number(risk.max_daily_loss||.015)*100,1)}% day - ${number(Number(risk.max_weekly_loss||.04)*100,0)}% week`;const model=report.probabilistic||{};$("model").textContent=String(model.status||"collecting_data").replaceAll("_"," ").toUpperCase();$("model-note").textContent=model.can_trade?"Bootstrap active; models shadow-only":"Validated models required";const luna=report.luna||{};$("luna").textContent=luna.ready?"READY":"FAIL CLOSED";$("luna-note").textContent=luna.policy?`${luna.policy.regime} - ${luna.policy.action}`:(luna.reason||"Waiting for policy");scanner(report.scanner||[]);events("operations",report.operations||[]);events("audit",report.audit||[]);canvas("equity-chart",(report.equity_curve||[]).map(x=>Number(x.equity)),"#f3b74f");const select=$("symbol"),current=select.value,keys=Object.keys(stream.symbols||{});select.replaceChildren(...keys.map(key=>{const o=document.createElement("option");o.value=key;o.textContent=key;return o}));if(keys.includes(current))select.value=current;market()}
async function refresh(){try{const response=await fetch("/api/meme",{cache:"no-store"});if(!response.ok)throw Error("API unavailable");render(await response.json())}catch(error){$("empty-copy").textContent=error.message}}
$("symbol").addEventListener("change",market);window.addEventListener("resize",()=>payload&&render(payload));refresh();setInterval(refresh,2000);
